import { User, Conversation, Message, Notification } from '../utils/types';

// ---- Current User (the logged-in user) ----
export const currentUser: User = {
  id: 'user-self',
  username: 'alex.johnson',
  password: 'hinge2006',
  displayName: 'Alex Johnson',
  age: 27,
  gender: 'Male',
  city: 'New York, NY',
  state: 'NY',
  profession: 'Software Engineer',
  company: 'TechStart Inc.',
  education: "Bachelor's Degree",
  aboutMe: "Hey there! I'm Alex, a software engineer who loves building things and exploring the city. When I'm not coding, you'll find me at a jazz club, trying a new restaurant, or hiking upstate. I'm looking for someone who loves good conversation and isn't afraid to be themselves. Let's grab coffee and see where things go!",
  interests: ['Technology', 'Music', 'Cooking', 'Hiking', 'Photography', 'Travel', 'Coffee'],
  music: ['Coldplay', 'The Killers', 'Jack Johnson', 'Death Cab for Cutie', 'Kanye West'],
  movies: ['Eternal Sunshine of the Spotless Mind', 'Garden State', 'Lost in Translation', 'The Departed'],
  books: ['The Alchemist', 'Freakonomics', 'A Short History of Nearly Everything'],
  relationshipGoal: 'Long-term Relationship',
  testimonials: [],
  photos: ['self-1', 'self-2', 'self-3'],
  avatar: 'self-1',
  status: 'Online',
  statusMessage: 'Looking for meaningful connections ✨',
  lastActive: new Date().toISOString(),
  joinDate: '2006-03-15T00:00:00.000Z',
  profileViews: 342,
};

// ---- 20 Sample Users ----
export const sampleUsers: User[] = [
  {
    id: 'user-01',
    username: 'emma.wilson',
    password: 'pass123',
    displayName: 'Emma Wilson',
    age: 25,
    gender: 'Female',
    city: 'New York, NY',
    state: 'NY',
    profession: 'Graphic Designer',
    company: 'CreativeWorks Studio',
    education: "Bachelor's Degree",
    aboutMe: "Creative soul with a passion for design and storytelling. I spend my weekends exploring galleries, sketching in Central Park, and finding the best brunch spots in Brooklyn. I believe the best relationships start with a shared love of art and good food. If you can recommend a good book or a hidden gem restaurant, we'll get along great!",
    interests: ['Art', 'Photography', 'Coffee', 'Travel', 'Reading', 'Yoga'],
    music: ['Norah Jones', 'Feist', 'The Postal Service', 'Belle and Sebastian'],
    movies: ['Amélie', 'Spirited Away', 'Lost in Translation', 'Before Sunset'],
    books: ['The Bell Jar', 'Norwegian Wood', 'The Unbearable Lightness of Being'],
    relationshipGoal: 'Long-term Relationship',
    testimonials: [
      { from: 'Sarah M.', fromId: 'user-05', text: "Emma is the sweetest person you'll ever meet. Any guy would be lucky to date her!", date: '2006-08-12T00:00:00.000Z' },
    ],
    photos: ['emma-1', 'emma-2', 'emma-3', 'emma-4'],
    avatar: 'emma-1',
    status: 'Online',
    statusMessage: 'Creating something beautiful 🎨',
    lastActive: '2006-09-20T14:30:00.000Z',
    joinDate: '2006-04-10T00:00:00.000Z',
    profileViews: 487,
  },
  {
    id: 'user-02',
    username: 'michael.chen',
    password: 'pass123',
    displayName: 'Michael Chen',
    age: 29,
    gender: 'Male',
    city: 'San Francisco, CA',
    state: 'CA',
    profession: 'Financial Analyst',
    company: 'Goldman Sachs',
    education: "Master's Degree",
    aboutMe: "Numbers guy by day, foodie adventurer by night. I've been to 15 countries and counting. I love a good debate about anything from economics to the best dim sum in the city. Looking for someone who's equally ambitious and knows how to have fun.",
    interests: ['Travel', 'Cooking', 'Wine', 'Fitness', 'Reading', 'Hiking'],
    music: ['John Mayer', 'Dave Matthews Band', 'U2', 'Radiohead'],
    movies: ['The Shawshank Redemption', 'Fight Club', 'Memento', 'Catch Me If You Can'],
    books: ['Freakonomics', 'The Tipping Point', "Ender's Game"],
    relationshipGoal: 'Long-term Relationship',
    testimonials: [],
    photos: ['michael-1', 'michael-2', 'michael-3'],
    avatar: 'michael-1',
    status: 'Away',
    statusMessage: 'Probably at the gym 💪',
    lastActive: '2006-09-20T10:15:00.000Z',
    joinDate: '2006-05-01T00:00:00.000Z',
    profileViews: 312,
  },
  {
    id: 'user-03',
    username: 'sarah.martinez',
    password: 'pass123',
    displayName: 'Sarah Martinez',
    age: 26,
    gender: 'Female',
    city: 'Chicago, IL',
    state: 'IL',
    profession: 'Teacher',
    company: 'Lincoln Park Elementary',
    education: "Master's Degree",
    aboutMe: "Third-grade teacher who believes every day is a chance to learn something new. I'm obsessed with live music, farmers markets, and my golden retriever Max. Looking for someone kind, genuine, and who doesn't mind dog hair on everything.",
    interests: ['Music', 'Cooking', 'Yoga', 'Reading', 'Volunteering', 'Hiking', 'Dancing'],
    music: ['Green Day', 'Fall Out Boy', 'Jack Johnson', 'Alicia Keys', 'Maroon 5'],
    movies: ['Love Actually', 'The Notebook', 'School of Rock', 'Finding Nemo'],
    books: ['To Kill a Mockingbird', 'Harry Potter', 'The Kite Runner'],
    relationshipGoal: 'Marriage',
    testimonials: [
      { from: 'Lisa K.', fromId: 'user-08', text: 'Sarah is the most genuine person I know. Her students adore her!', date: '2006-07-15T00:00:00.000Z' },
    ],
    photos: ['sarah-1', 'sarah-2', 'sarah-3', 'sarah-4', 'sarah-5'],
    avatar: 'sarah-1',
    status: 'Online',
    statusMessage: 'Just baked cookies! 🍪',
    lastActive: '2006-09-20T16:45:00.000Z',
    joinDate: '2006-03-20T00:00:00.000Z',
    profileViews: 523,
  },
  {
    id: 'user-04',
    username: 'james.oconnor',
    password: 'pass123',
    displayName: "James O'Connor",
    age: 31,
    gender: 'Male',
    city: 'Boston, MA',
    state: 'MA',
    profession: 'Architect',
    company: 'Hawkins & Associates',
    education: "Master's Degree",
    aboutMe: "I design buildings by day and explore them by night. Boston is my playground — from the brownstones of Back Bay to the waterfront. I'm a history nerd, amateur chef, and terrible but enthusiastic dancer. Let's explore the city together.",
    interests: ['Art', 'Photography', 'Cooking', 'Travel', 'Theater', 'Running', 'Coffee'],
    music: ['The Strokes', 'Arctic Monkeys', 'Bloc Party', 'Franz Ferdinand'],
    movies: ['The Royal Tenenbaums', 'Good Will Hunting', 'Inception', 'Ratatouille'],
    books: ['Invisible Cities', 'The Great Gatsby', 'Zen and the Art of Motorcycle Maintenance'],
    relationshipGoal: 'Long-term Relationship',
    testimonials: [],
    photos: ['james-1', 'james-2', 'james-3'],
    avatar: 'james-1',
    status: 'Offline',
    statusMessage: 'Sketching blueprints ✏️',
    lastActive: '2006-09-19T22:00:00.000Z',
    joinDate: '2006-06-05T00:00:00.000Z',
    profileViews: 278,
  },
  {
    id: 'user-05',
    username: 'olivia.park',
    password: 'pass123',
    displayName: 'Olivia Park',
    age: 24,
    gender: 'Female',
    city: 'Los Angeles, CA',
    state: 'CA',
    profession: 'Photographer',
    company: 'Freelance',
    education: "Bachelor's Degree",
    aboutMe: "I see the world through a lens. Whether it's a sunset over Santa Monica or a candid moment at a coffee shop, I'm always looking for the next great shot. I love road trips, vinyl records, and deep conversations. If you're up for an adventure, let's talk!",
    interests: ['Photography', 'Travel', 'Music', 'Coffee', 'Surfing', 'Art', 'Fashion'],
    music: ['The Shins', 'Modest Mouse', 'Yeah Yeah Yeahs', 'M.I.A.', 'LCD Soundsystem'],
    movies: ['Garden State', 'Rushmore', 'Donnie Darko', 'Kill Bill'],
    books: ['On the Road', 'The Perks of Being a Wallflower', 'A Heartbreaking Work of Staggering Genius'],
    relationshipGoal: 'Something Casual',
    testimonials: [
      { from: 'Emma W.', fromId: 'user-01', text: "Olivia's photos are incredible. She has such a unique way of seeing the world.", date: '2006-09-01T00:00:00.000Z' },
    ],
    photos: ['olivia-1', 'olivia-2', 'olivia-3', 'olivia-4'],
    avatar: 'olivia-1',
    status: 'Online',
    statusMessage: 'Golden hour hunting 📷',
    lastActive: '2006-09-20T17:00:00.000Z',
    joinDate: '2006-07-01T00:00:00.000Z',
    profileViews: 612,
  },
  {
    id: 'user-06',
    username: 'david.thompson',
    password: 'pass123',
    displayName: 'David Thompson',
    age: 28,
    gender: 'Male',
    city: 'Seattle, WA',
    state: 'WA',
    profession: 'Software Engineer',
    company: 'Amazon',
    education: "Bachelor's Degree",
    aboutMe: "Pacific Northwest native who runs on coffee and curiosity. When I'm not writing code, I'm hiking Mount Rainier, playing guitar, or discovering new indie bands. I'm looking for someone who can appreciate a rainy day with a good book and a cup of coffee.",
    interests: ['Technology', 'Music', 'Hiking', 'Coffee', 'Gaming', 'Board Games', 'Cycling'],
    music: ['Radiohead', 'Arcade Fire', 'Death Cab for Cutie', 'Sufjan Stevens'],
    movies: ['Eternal Sunshine of the Spotless Mind', 'The Matrix', 'Blade Runner'],
    books: ['Snow Crash', 'Cryptonomicon', 'The Hitchhiker\'s Guide to the Galaxy'],
    relationshipGoal: 'Long-term Relationship',
    testimonials: [],
    photos: ['david-1', 'david-2', 'david-3'],
    avatar: 'david-1',
    status: 'Online',
    statusMessage: 'Debugging life, one line at a time 🖥️',
    lastActive: '2006-09-20T15:30:00.000Z',
    joinDate: '2006-04-20T00:00:00.000Z',
    profileViews: 295,
  },
  {
    id: 'user-07',
    username: 'rachel.kim',
    password: 'pass123',
    displayName: 'Rachel Kim',
    age: 27,
    gender: 'Female',
    city: 'New York, NY',
    state: 'NY',
    profession: 'Marketing Manager',
    company: 'Ogilvy & Mather',
    education: "Bachelor's Degree",
    aboutMe: "Marketing nerd by day, Broadway enthusiast by night. I've seen Hamilton... just kidding, it's 2006! But I have seen Wicked three times. I love trying new restaurants, hosting dinner parties, and debating whether The Office or Arrested Development is funnier (it's The Office).",
    interests: ['Theater', 'Cooking', 'Wine', 'Fashion', 'Travel', 'Dancing', 'Writing'],
    music: ['Beyoncé', 'Gwen Stefani', 'Amy Winehouse', 'Justin Timberlake'],
    movies: ['The Devil Wears Prada', 'Mean Girls', 'Moulin Rouge!', 'Chicago'],
    books: ['The Devil Wears Prada', 'Blink', 'The Tipping Point'],
    relationshipGoal: 'Long-term Relationship',
    testimonials: [
      { from: 'Emma W.', fromId: 'user-01', text: 'Rachel throws the best dinner parties in Manhattan!', date: '2006-08-20T00:00:00.000Z' },
    ],
    photos: ['rachel-1', 'rachel-2', 'rachel-3', 'rachel-4'],
    avatar: 'rachel-1',
    status: 'Away',
    statusMessage: 'At a Broadway show 🎭',
    lastActive: '2006-09-20T19:00:00.000Z',
    joinDate: '2006-05-15T00:00:00.000Z',
    profileViews: 445,
  },
  {
    id: 'user-08',
    username: 'lisa.nguyen',
    password: 'pass123',
    displayName: 'Lisa Nguyen',
    age: 25,
    gender: 'Female',
    city: 'Austin, TX',
    state: 'TX',
    profession: 'Writer',
    company: 'Austin Chronicle',
    education: "Bachelor's Degree",
    aboutMe: "Words are my thing. I write about food, music, and culture for the Austin Chronicle. When I'm not on deadline, I'm at a live music venue, trying a new taco truck, or kayaking on Lady Bird Lake. Looking for someone who loves to explore and can keep up with my SXSW schedule.",
    interests: ['Writing', 'Music', 'Cooking', 'Travel', 'Yoga', 'Photography'],
    music: ['Spoon', 'Explosions in the Sky', 'Bright Eyes', 'Iron & Wine', 'Neko Case'],
    movies: ['Dazed and Confused', 'Before Sunrise', 'Slacker', 'Sideways'],
    books: ['A Moveable Feast', 'Kitchen Confidential', 'The Omnivore\'s Dilemma'],
    relationshipGoal: 'Not Sure Yet',
    testimonials: [],
    photos: ['lisa-1', 'lisa-2', 'lisa-3'],
    avatar: 'lisa-1',
    status: 'Online',
    statusMessage: 'Writing at a coffee shop ☕',
    lastActive: '2006-09-20T12:00:00.000Z',
    joinDate: '2006-06-01T00:00:00.000Z',
    profileViews: 367,
  },
  {
    id: 'user-09',
    username: 'ryan.patel',
    password: 'pass123',
    displayName: 'Ryan Patel',
    age: 30,
    gender: 'Male',
    city: 'Denver, CO',
    state: 'CO',
    profession: 'Doctor',
    company: 'Denver Health Medical Center',
    education: 'PhD',
    aboutMe: "ER doctor who somehow still finds time to snowboard, cook elaborate meals, and maintain a fantasy football team. I'm looking for someone who's as passionate about their career as they are about living life to the fullest. Bonus points if you can handle my terrible schedule.",
    interests: ['Skiing', 'Cooking', 'Fitness', 'Travel', 'Sports', 'Hiking', 'Wine'],
    music: ['Coldplay', 'Snow Patrol', 'The Fray', 'Dashboard Confessional'],
    movies: ['The Lord of the Rings', 'Gladiator', 'The Departed', 'Casino Royale'],
    books: ['Mountains Beyond Mountains', 'When Breath Becomes Air', 'The House of God'],
    relationshipGoal: 'Marriage',
    testimonials: [
      { from: 'Mike T.', fromId: 'user-14', text: 'Ryan saved my life in the ER and then invited me to his Super Bowl party. Stand-up guy.', date: '2006-06-10T00:00:00.000Z' },
    ],
    photos: ['ryan-1', 'ryan-2', 'ryan-3', 'ryan-4'],
    avatar: 'ryan-1',
    status: 'Busy',
    statusMessage: 'On shift at the hospital 🏥',
    lastActive: '2006-09-20T08:00:00.000Z',
    joinDate: '2006-04-01T00:00:00.000Z',
    profileViews: 398,
  },
  {
    id: 'user-10',
    username: 'jessica.taylor',
    password: 'pass123',
    displayName: 'Jessica Taylor',
    age: 26,
    gender: 'Female',
    city: 'Portland, OR',
    state: 'OR',
    profession: 'Chef',
    company: 'Pok Pok',
    education: 'Trade School',
    aboutMe: "Culinary school grad turned sous chef. I think the way to anyone's heart is through their stomach. I'm obsessed with farm-to-table cooking, foraging for mushrooms, and experimenting with Thai cuisine. When I'm not in the kitchen, I'm biking around Portland or visiting wineries in the Willamette Valley.",
    interests: ['Cooking', 'Wine', 'Cycling', 'Hiking', 'Yoga', 'Art', 'Volunteering'],
    music: ['The Decemberists', 'Elliott Smith', 'Cat Power', 'Joanna Newsom'],
    movies: ['Big Night', 'Julie & Julia', 'Ratatouille', 'Willy Wonka'],
    books: ['Kitchen Confidential', 'Heat', 'My Life in France'],
    relationshipGoal: 'Long-term Relationship',
    testimonials: [],
    photos: ['jessica-1', 'jessica-2', 'jessica-3'],
    avatar: 'jessica-1',
    status: 'Offline',
    statusMessage: 'Prepping for dinner service 🍳',
    lastActive: '2006-09-19T23:30:00.000Z',
    joinDate: '2006-07-10T00:00:00.000Z',
    profileViews: 334,
  },
  {
    id: 'user-11',
    username: 'chris.brown',
    password: 'pass123',
    displayName: 'Chris Anderson',
    age: 32,
    gender: 'Male',
    city: 'Miami, FL',
    state: 'FL',
    profession: 'Musician',
    company: 'Independent',
    education: "Bachelor's Degree",
    aboutMe: "Singer-songwriter who plays way too many open mics. I grew up on the beach and still spend every free moment in the ocean. Music, waves, and good vibes — that's my life philosophy. Looking for someone who doesn't mind sand in the car and guitar picks everywhere.",
    interests: ['Music', 'Surfing', 'Travel', 'Photography', 'Fitness', 'Coffee'],
    music: ['Bob Marley', 'Jack Johnson', 'Ben Harper', 'G. Love', 'Sublime'],
    movies: ['Almost Famous', 'Endless Summer', 'School of Rock', 'Walk the Line'],
    books: ['Scar Tissue', 'Chronicles: Volume One', 'This Is Your Brain on Music'],
    relationshipGoal: 'Something Casual',
    testimonials: [],
    photos: ['chris-1', 'chris-2', 'chris-3'],
    avatar: 'chris-1',
    status: 'Online',
    statusMessage: 'Playing at The Fillmore tonight 🎸',
    lastActive: '2006-09-20T20:00:00.000Z',
    joinDate: '2006-05-20T00:00:00.000Z',
    profileViews: 456,
  },
  {
    id: 'user-12',
    username: 'amanda.lewis',
    password: 'pass123',
    displayName: 'Amanda Lewis',
    age: 28,
    gender: 'Female',
    city: 'Washington, DC',
    state: 'DC',
    profession: 'Lawyer',
    company: 'Kirkland & Ellis',
    education: "Master's Degree",
    aboutMe: "Corporate lawyer who moonlights as a wine enthusiast and half-marathon runner. I love a good debate (occupational hazard), exploring DC's amazing museum scene, and hosting wine-and-cheese nights. Looking for someone intelligent, driven, and who can make me laugh after a long day in court.",
    interests: ['Running', 'Wine', 'Reading', 'Travel', 'Theater', 'Cooking', 'Art'],
    music: ['Norah Jones', 'Alicia Keys', 'John Legend', 'Jamie Cullum'],
    movies: ['Legally Blonde', 'A Few Good Men', 'The West Wing', 'My Cousin Vinny'],
    books: ['To Kill a Mockingbird', 'Outliers', 'The Art of Advocacy'],
    relationshipGoal: 'Marriage',
    testimonials: [
      { from: 'Rachel K.', fromId: 'user-07', text: 'Amanda is brilliant and hilarious. The total package!', date: '2006-09-05T00:00:00.000Z' },
    ],
    photos: ['amanda-1', 'amanda-2', 'amanda-3', 'amanda-4'],
    avatar: 'amanda-1',
    status: 'Online',
    statusMessage: 'Just finished a 10K run! 🏃‍♀️',
    lastActive: '2006-09-20T18:00:00.000Z',
    joinDate: '2006-03-25T00:00:00.000Z',
    profileViews: 501,
  },
  {
    id: 'user-13',
    username: 'kevin.wright',
    password: 'pass123',
    displayName: 'Kevin Wright',
    age: 27,
    gender: 'Male',
    city: 'Chicago, IL',
    state: 'IL',
    profession: 'Consultant',
    company: 'McKinsey & Company',
    education: "Master's Degree",
    aboutMe: "Management consultant who's trying to solve the world's problems one PowerPoint at a time. When I'm off the clock, I'm exploring Chicago's food scene, playing pickup basketball, or binge-watching Lost. I'm looking for someone smart, funny, and who won't judge my deep-dish pizza addiction.",
    interests: ['Sports', 'Cooking', 'Travel', 'Reading', 'Gaming', 'Coffee', 'Board Games'],
    music: ['Kanye West', 'OutKast', 'The Roots', 'Common', 'Lupe Fiasco'],
    movies: ['The Godfather', 'Goodfellas', 'Thank You for Smoking', 'Office Space'],
    books: ['Good to Great', 'The World Is Flat', 'Moneyball'],
    relationshipGoal: 'Long-term Relationship',
    testimonials: [],
    photos: ['kevin-1', 'kevin-2', 'kevin-3'],
    avatar: 'kevin-1',
    status: 'Away',
    statusMessage: 'Traveling for work ✈️',
    lastActive: '2006-09-20T09:00:00.000Z',
    joinDate: '2006-05-30T00:00:00.000Z',
    profileViews: 289,
  },
  {
    id: 'user-14',
    username: 'megan.clark',
    password: 'pass123',
    displayName: 'Megan Clark',
    age: 24,
    gender: 'Female',
    city: 'San Francisco, CA',
    state: 'CA',
    profession: 'Research Scientist',
    company: 'Stanford University',
    education: 'PhD',
    aboutMe: "Neuroscience PhD student who geeks out about the brain and then geeks out about rock climbing. I love science puns (they're sodium funny), craft beer, and spontaneous road trips. Looking for someone curious about the world who doesn't mind hearing about neurons over dinner.",
    interests: ['Technology', 'Hiking', 'Reading', 'Coffee', 'Cycling', 'Board Games', 'Travel'],
    music: ['Radiohead', 'Björk', 'Portishead', 'Massive Attack', 'Muse'],
    movies: ['A Beautiful Mind', 'Primer', 'Donnie Darko', 'The Prestige'],
    books: ['Gödel, Escher, Bach', 'The Man Who Mistook His Wife for a Hat', 'Cosmos'],
    relationshipGoal: 'Long-term Relationship',
    testimonials: [],
    photos: ['megan-1', 'megan-2', 'megan-3', 'megan-4'],
    avatar: 'megan-1',
    status: 'Online',
    statusMessage: 'Lab results are in! 🔬',
    lastActive: '2006-09-20T16:00:00.000Z',
    joinDate: '2006-06-15T00:00:00.000Z',
    profileViews: 378,
  },
  {
    id: 'user-15',
    username: 'tyler.brooks',
    password: 'pass123',
    displayName: 'Tyler Brooks',
    age: 29,
    gender: 'Male',
    city: 'Los Angeles, CA',
    state: 'CA',
    profession: 'Marketing Manager',
    company: 'Red Bull',
    education: "Bachelor's Degree",
    aboutMe: "Marketing guy at Red Bull which means I get paid to go to extreme sports events. Pretty sweet deal. When I'm not working, I'm surfing in Malibu, playing volleyball on the beach, or exploring LA's taco scene. I don't take life too seriously and I'm looking for someone with the same vibe.",
    interests: ['Surfing', 'Sports', 'Photography', 'Travel', 'Fitness', 'Music', 'Cooking'],
    music: ['Red Hot Chili Peppers', 'Blink-182', 'Sublime', '311', 'Incubus'],
    movies: ['Top Gun', 'Point Break', 'Anchorman', 'Zoolander'],
    books: ['Into the Wild', 'Born to Run', 'Barbarian Days'],
    relationshipGoal: 'Something Casual',
    testimonials: [],
    photos: ['tyler-1', 'tyler-2', 'tyler-3'],
    avatar: 'tyler-1',
    status: 'Online',
    statusMessage: 'Surf report looking good! 🏄',
    lastActive: '2006-09-20T11:00:00.000Z',
    joinDate: '2006-07-20T00:00:00.000Z',
    profileViews: 423,
  },
  {
    id: 'user-16',
    username: 'nicole.foster',
    password: 'pass123',
    displayName: 'Nicole Foster',
    age: 26,
    gender: 'Female',
    city: 'Boston, MA',
    state: 'MA',
    profession: 'Nurse',
    company: 'Massachusetts General Hospital',
    education: "Bachelor's Degree",
    aboutMe: "Pediatric nurse who believes in the healing power of laughter (and modern medicine). I spend my free time sailing on the Charles, volunteering at animal shelters, and mastering my grandmother's Italian recipes. Looking for someone kind, patient, and who loves Sunday morning farmers markets.",
    interests: ['Volunteering', 'Cooking', 'Yoga', 'Reading', 'Travel', 'Coffee', 'Art'],
    music: ['Damien Rice', 'The Cranberries', 'Sarah McLachlan', 'Jason Mraz'],
    movies: ['Patch Adams', 'Love Actually', "P.S. I Love You", 'The Notebook'],
    books: ['The Time Traveler\'s Wife', 'A Thousand Splendid Suns', 'Eat Pray Love'],
    relationshipGoal: 'Marriage',
    testimonials: [
      { from: 'James O.', fromId: 'user-04', text: 'Nicole is one of the kindest people I know. She makes everyone around her better.', date: '2006-08-25T00:00:00.000Z' },
    ],
    photos: ['nicole-1', 'nicole-2', 'nicole-3', 'nicole-4'],
    avatar: 'nicole-1',
    status: 'Online',
    statusMessage: 'Just adopted a kitten! 🐱',
    lastActive: '2006-09-20T13:30:00.000Z',
    joinDate: '2006-04-15T00:00:00.000Z',
    profileViews: 467,
  },
  {
    id: 'user-17',
    username: 'jason.murphy',
    password: 'pass123',
    displayName: 'Jason Murphy',
    age: 33,
    gender: 'Male',
    city: 'Philadelphia, PA',
    state: 'PA',
    profession: 'Chef',
    company: 'Zahav Restaurant',
    education: 'Trade School',
    aboutMe: "Head chef who lives and breathes food. I trained in Italy and brought my love of Mediterranean cuisine back to Philly. When I'm not in the kitchen, I'm at the Italian Market, riding my bike along the Schuylkill, or arguing about why cheesesteaks are overrated (controversial, I know).",
    interests: ['Cooking', 'Wine', 'Cycling', 'Travel', 'Music', 'Art', 'Photography'],
    music: ['Tom Waits', 'Nick Cave', 'Leonard Cohen', 'Johnny Cash'],
    movies: ['Big Night', 'Goodfellas', 'Rocky', 'The Italian Job'],
    books: ['Kitchen Confidential', 'On Food and Cooking', 'Heat'],
    relationshipGoal: 'Long-term Relationship',
    testimonials: [],
    photos: ['jason-1', 'jason-2', 'jason-3'],
    avatar: 'jason-1',
    status: 'Offline',
    statusMessage: 'Dinner service time! 🍝',
    lastActive: '2006-09-19T21:00:00.000Z',
    joinDate: '2006-06-20T00:00:00.000Z',
    profileViews: 356,
  },
  {
    id: 'user-18',
    username: 'ashley.wong',
    password: 'pass123',
    displayName: 'Ashley Wong',
    age: 25,
    gender: 'Female',
    city: 'New York, NY',
    state: 'NY',
    profession: 'Financial Analyst',
    company: 'JPMorgan Chase',
    education: "Bachelor's Degree",
    aboutMe: "Wall Street by day, foodie blogger by night. I'm on a mission to eat at every restaurant in Manhattan (halfway there!). I love rooftop happy hours, weekend getaways to the Hamptons, and getting way too competitive at trivia night. Looking for someone ambitious who knows how to have fun.",
    interests: ['Cooking', 'Wine', 'Travel', 'Fitness', 'Fashion', 'Dancing', 'Coffee'],
    music: ['Rihanna', 'Shakira', 'Black Eyed Peas', 'Pussycat Dolls', 'Gwen Stefani'],
    movies: ['Sex and the City', 'The Devil Wears Prada', 'Breakfast at Tiffany\'s', 'Clueless'],
    books: ['Confessions of a Shopaholic', 'Rich Dad Poor Dad', 'The Tipping Point'],
    relationshipGoal: 'Long-term Relationship',
    testimonials: [],
    photos: ['ashley-1', 'ashley-2', 'ashley-3', 'ashley-4'],
    avatar: 'ashley-1',
    status: 'Online',
    statusMessage: 'Trivia night champion! 🏆',
    lastActive: '2006-09-20T21:00:00.000Z',
    joinDate: '2006-05-10T00:00:00.000Z',
    profileViews: 534,
  },
  {
    id: 'user-19',
    username: 'marcus.rivera',
    password: 'pass123',
    displayName: 'Marcus Rivera',
    age: 28,
    gender: 'Male',
    city: 'Austin, TX',
    state: 'TX',
    profession: 'Graphic Designer',
    company: 'Pentagram',
    education: "Bachelor's Degree",
    aboutMe: "Designer and illustrator who moved to Austin for the tacos and stayed for the music. I'm usually at a show, sketching at a coffee shop, or teaching myself to cook something new. I believe good design makes the world better and that breakfast tacos are a food group.",
    interests: ['Art', 'Music', 'Coffee', 'Technology', 'Photography', 'Cooking', 'Cycling'],
    music: ['Gorillaz', 'Daft Punk', 'Justice', 'LCD Soundsystem', 'TV on the Radio'],
    movies: ['Spirited Away', 'Eternal Sunshine', 'Waking Life', 'A Scanner Darkly'],
    books: ['Steal Like an Artist', 'The Design of Everyday Things', 'Understanding Comics'],
    relationshipGoal: 'Not Sure Yet',
    testimonials: [],
    photos: ['marcus-1', 'marcus-2', 'marcus-3'],
    avatar: 'marcus-1',
    status: 'Away',
    statusMessage: 'Sketching at Jo\'s Coffee ✏️',
    lastActive: '2006-09-20T14:00:00.000Z',
    joinDate: '2006-07-05T00:00:00.000Z',
    profileViews: 301,
  },
  {
    id: 'user-20',
    username: 'stephanie.hill',
    password: 'pass123',
    displayName: 'Stephanie Hill',
    age: 27,
    gender: 'Female',
    city: 'Seattle, WA',
    state: 'WA',
    profession: 'Software Engineer',
    company: 'Microsoft',
    education: "Master's Degree",
    aboutMe: "Software engineer at Microsoft who swears she uses Firefox at home. I love board game nights, hiking the Pacific Crest Trail, and debating Star Wars vs. Star Trek (Trek, obviously). Looking for a fellow nerd who appreciates a good algorithm and a great cup of coffee.",
    interests: ['Technology', 'Gaming', 'Board Games', 'Hiking', 'Coffee', 'Reading', 'Cooking'],
    music: ['Death Cab for Cutie', 'Modest Mouse', 'The Postal Service', 'Iron & Wine'],
    movies: ['The Lord of the Rings', 'Star Wars', 'The Princess Bride', 'Serenity'],
    books: ['Neuromancer', 'Dune', 'The Hitchhiker\'s Guide to the Galaxy', 'Ender\'s Game'],
    relationshipGoal: 'Long-term Relationship',
    testimonials: [
      { from: 'David T.', fromId: 'user-06', text: "Steph is the best coder I know and she'll absolutely destroy you at Settlers of Catan.", date: '2006-09-10T00:00:00.000Z' },
    ],
    photos: ['stephanie-1', 'stephanie-2', 'stephanie-3', 'stephanie-4'],
    avatar: 'stephanie-1',
    status: 'Online',
    statusMessage: 'Just shipped a new feature! 🚀',
    lastActive: '2006-09-20T17:30:00.000Z',
    joinDate: '2006-04-25T00:00:00.000Z',
    profileViews: 412,
  },
];

// ---- Pre-existing conversations ----
export const sampleConversations: Conversation[] = [
  {
    id: 'conv-01',
    participants: ['user-self', 'user-01'],
    lastActivity: '2006-09-20T14:35:00.000Z',
    messages: [
      { id: 'msg-001', conversationId: 'conv-01', senderId: 'user-self', text: "Hey Emma! I noticed we both love photography and coffee. What's your favorite coffee shop in the city?", timestamp: '2006-09-18T10:00:00.000Z', type: 'text', read: true },
      { id: 'msg-002', conversationId: 'conv-01', senderId: 'user-01', text: "Hi Alex! Oh I love this question. I'm obsessed with this tiny place in the East Village called Mud Coffee. Have you been?", timestamp: '2006-09-18T10:15:00.000Z', type: 'text', read: true },
      { id: 'msg-003', conversationId: 'conv-01', senderId: 'user-self', text: "No way, I walk past Mud all the time but never went in! I'll have to check it out. What do you usually order?", timestamp: '2006-09-18T10:22:00.000Z', type: 'text', read: true },
      { id: 'msg-004', conversationId: 'conv-01', senderId: 'user-01', text: "Their lavender latte is incredible. I usually go there to sketch on weekends. Maybe we could meet up there sometime? :)", timestamp: '2006-09-18T10:30:00.000Z', type: 'text', read: true },
      { id: 'msg-005', conversationId: 'conv-01', senderId: 'user-self', text: "I'd love that! How about this Saturday around 11?", timestamp: '2006-09-18T11:00:00.000Z', type: 'text', read: true },
      { id: 'msg-006', conversationId: 'conv-01', senderId: 'user-01', text: "It's a date! See you there. I'll be the one with the sketchbook and paint-stained fingers 😊", timestamp: '2006-09-18T11:10:00.000Z', type: 'text', read: true },
      { id: 'msg-007', conversationId: 'conv-01', senderId: 'user-self', text: "Can't wait! By the way, I checked out your photography portfolio link. Your Central Park series is stunning.", timestamp: '2006-09-20T14:20:00.000Z', type: 'text', read: true },
      { id: 'msg-008', conversationId: 'conv-01', senderId: 'user-01', text: "Aww thank you! That means a lot. Photography is my happy place. What kind of photos do you like to take?", timestamp: '2006-09-20T14:35:00.000Z', type: 'text', read: false },
    ],
  },
  {
    id: 'conv-02',
    participants: ['user-self', 'user-07'],
    lastActivity: '2006-09-19T20:45:00.000Z',
    messages: [
      { id: 'msg-009', conversationId: 'conv-02', senderId: 'user-07', text: "Hey Alex! I see you're a fellow New Yorker. The Office or Arrested Development?", timestamp: '2006-09-19T19:00:00.000Z', type: 'text', read: true },
      { id: 'msg-010', conversationId: 'conv-02', senderId: 'user-self', text: "Oh that's tough! I love both, but I gotta go with The Office. Michael Scott is a national treasure.", timestamp: '2006-09-19T19:15:00.000Z', type: 'text', read: true },
      { id: 'msg-011', conversationId: 'conv-02', senderId: 'user-07', text: "YES! Correct answer 😆 Have you seen the new season? Jim and Pam are KILLING me.", timestamp: '2006-09-19T19:20:00.000Z', type: 'text', read: true },
      { id: 'msg-012', conversationId: 'conv-02', senderId: 'user-self', text: "I know right?! They need to get together already. So what else are you into besides great TV?", timestamp: '2006-09-19T19:30:00.000Z', type: 'text', read: true },
      { id: 'msg-013', conversationId: 'conv-02', senderId: 'user-07', text: "I'm a total Broadway nerd. Just saw Wicked for the third time last week. And I love hosting dinner parties. You should come to one!", timestamp: '2006-09-19T20:00:00.000Z', type: 'text', read: true },
      { id: 'msg-014', conversationId: 'conv-02', senderId: 'user-self', text: "I'd love that! I make a pretty mean risotto if I do say so myself 😄", timestamp: '2006-09-19T20:30:00.000Z', type: 'text', read: true },
      { id: 'msg-015', conversationId: 'conv-02', senderId: 'user-07', text: "A man who cooks?! You're hired. Next dinner party is this Friday. You're officially invited.", timestamp: '2006-09-19T20:45:00.000Z', type: 'text', read: false },
    ],
  },
  {
    id: 'conv-03',
    participants: ['user-self', 'user-03'],
    lastActivity: '2006-09-17T15:00:00.000Z',
    messages: [
      { id: 'msg-016', conversationId: 'conv-03', senderId: 'user-self', text: "Hi Sarah! I love that you're a teacher. What got you into education?", timestamp: '2006-09-17T12:00:00.000Z', type: 'text', read: true },
      { id: 'msg-017', conversationId: 'conv-03', senderId: 'user-03', text: "Hi Alex! Thanks for reaching out :) I've always loved working with kids. There's nothing better than that moment when something clicks for a student. What about you — what got you into tech?", timestamp: '2006-09-17T14:00:00.000Z', type: 'text', read: true },
      { id: 'msg-018', conversationId: 'conv-03', senderId: 'user-self', text: "I built my first website when I was 12 and I've been hooked ever since. There's something magical about creating something from nothing.", timestamp: '2006-09-17T14:30:00.000Z', type: 'text', read: true },
      { id: 'msg-019', conversationId: 'conv-03', senderId: 'user-03', text: "That's so cool! My students would love that. Maybe you could come talk to my class about coding sometime? They'd be so inspired!", timestamp: '2006-09-17T15:00:00.000Z', type: 'text', read: true },
    ],
  },
];

// ---- Notifications ----
export const sampleNotifications: Notification[] = [
  { id: 'notif-01', type: 'match', title: 'New Match!', text: 'You and Emma Wilson are a match! Send her a message.', timestamp: '2006-09-18T09:30:00.000Z', read: true, relatedUserId: 'user-01' },
  { id: 'notif-02', type: 'match', title: 'New Match!', text: "You and Rachel Kim are a match! Say hello.", timestamp: '2006-09-19T18:00:00.000Z', read: true, relatedUserId: 'user-07' },
  { id: 'notif-03', type: 'interest', title: 'Someone is interested!', text: 'A new person has expressed interest in your profile.', timestamp: '2006-09-20T08:00:00.000Z', read: false },
  { id: 'notif-04', type: 'view', title: 'Profile View', text: 'Ashley Wong viewed your profile.', timestamp: '2006-09-20T12:00:00.000Z', read: false, relatedUserId: 'user-18' },
  { id: 'notif-05', type: 'message', title: 'New Message', text: 'Emma Wilson sent you a message.', timestamp: '2006-09-20T14:35:00.000Z', read: false, relatedUserId: 'user-01' },
  { id: 'notif-06', type: 'system', title: 'Welcome to Hinge 2006!', text: 'Complete your profile to get better matches.', timestamp: '2006-03-15T00:00:00.000Z', read: true },
];

// Pre-seeded interests (who the current user has expressed interest in, and who has expressed interest back)
export const initialInterests = {
  // Users we expressed interest in
  sentInterests: ['user-01', 'user-03', 'user-07', 'user-12', 'user-14'],
  // Users who expressed interest in us
  receivedInterests: ['user-01', 'user-03', 'user-05', 'user-07', 'user-18', 'user-20'],
  // Mutual matches (intersection — already connected)
  matches: ['user-01', 'user-03', 'user-07'],
  // Users we skipped
  skippedUsers: ['user-11'],
};
